services:
  app:
    build: .
    ports:
      - "5001:5001"
    develop:
      watch:
        - action: rebuild
          path: cmd/
        - action: rebuild
          path: internal/
        - action: rebuild
          path: go.sum
    environment:
      - RATCHET_DATABASE_HOST=db
      - RATCHET_DATABASE_PORT=5432
      - RATCHET_DATABASE_USER=postgres
      - RATCHET_DATABASE_PASS=mypass
      - RATCHET_DATABASE_NAME=postgres
      - RATCHET_DATABASE_DISABLE_TLS=true
    env_file:
      - path: .env
        required: false
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
