[project]
name = "ratchet"
version = "0.1.0"
description = "AI bot to help reduce operational toil"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.0",
]
