CREATE TABLE team (
    id SERIAL PRIMARY KEY,          
    name VARCHAR(255) NOT NULL,    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
);
