// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channels.sql

package schema

import (
	"context"
)

const addChannel = `-- name: AddChannel :one
INSERT INTO channels (channel_id)
VALUES ($1)
ON CONFLICT (channel_id) DO UPDATE SET channel_id = channels.channel_id
RETURNING channel_id, created_at, latest_slack_ts
`

func (q *Queries) AddChannel(ctx context.Context, channelID string) (Channel, error) {
	row := q.db.QueryRow(ctx, addChannel, channelID)
	var i Channel
	err := row.Scan(&i.ChannelID, &i.CreatedAt, &i.LatestSlackTs)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT channel_id, created_at, latest_slack_ts FROM channels
WHERE channel_id = $1
`

func (q *Queries) GetChannel(ctx context.Context, channelID string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, channelID)
	var i Channel
	err := row.Scan(&i.ChannelID, &i.CreatedAt, &i.LatestSlackTs)
	return i, err
}

const getChannels = `-- name: GetChannels :many
SELECT channel_id, created_at, latest_slack_ts FROM channels
`

func (q *Queries) GetChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(&i.ChannelID, &i.CreatedAt, &i.LatestSlackTs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLatestSlackTs = `-- name: UpdateLatestSlackTs :exec
UPDATE channels
SET latest_slack_ts = $2
WHERE channel_id = $1
`

type UpdateLatestSlackTsParams struct {
	ChannelID     string
	LatestSlackTs string
}

func (q *Queries) UpdateLatestSlackTs(ctx context.Context, arg UpdateLatestSlackTsParams) error {
	_, err := q.db.Exec(ctx, updateLatestSlackTs, arg.ChannelID, arg.LatestSlackTs)
	return err
}
