// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: incidents.sql

package schema

import (
	"context"

	dto "github.com/dynoinc/ratchet/internal/storage/schema/dto"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeIncident = `-- name: CloseIncident :one
UPDATE incidents
SET end_timestamp = $1
WHERE incident_id = $2::integer
RETURNING incident_id
`

type CloseIncidentParams struct {
	EndTimestamp pgtype.Timestamptz
	IncidentID   int32
}

func (q *Queries) CloseIncident(ctx context.Context, arg CloseIncidentParams) (int32, error) {
	row := q.db.QueryRow(ctx, closeIncident, arg.EndTimestamp, arg.IncidentID)
	var incident_id int32
	err := row.Scan(&incident_id)
	return incident_id, err
}

const getLatestIncidentBeforeTimestamp = `-- name: GetLatestIncidentBeforeTimestamp :one
SELECT incident_id, channel_id, slack_ts, alert, service, priority, attrs, start_timestamp, end_timestamp
FROM incidents
WHERE channel_id = $1
  AND alert = $2
  AND service = $3
  AND start_timestamp < $4
  AND end_timestamp IS NULL
ORDER BY start_timestamp DESC
LIMIT 1
`

type GetLatestIncidentBeforeTimestampParams struct {
	ChannelID       string
	Alert           string
	Service         string
	BeforeTimestamp pgtype.Timestamptz
}

func (q *Queries) GetLatestIncidentBeforeTimestamp(ctx context.Context, arg GetLatestIncidentBeforeTimestampParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getLatestIncidentBeforeTimestamp,
		arg.ChannelID,
		arg.Alert,
		arg.Service,
		arg.BeforeTimestamp,
	)
	var i Incident
	err := row.Scan(
		&i.IncidentID,
		&i.ChannelID,
		&i.SlackTs,
		&i.Alert,
		&i.Service,
		&i.Priority,
		&i.Attrs,
		&i.StartTimestamp,
		&i.EndTimestamp,
	)
	return i, err
}

const getOpenIncidents = `-- name: GetOpenIncidents :many
SELECT incident_id, channel_id, slack_ts, alert, service, priority, attrs, start_timestamp, end_timestamp
FROM incidents
WHERE end_timestamp IS NULL
`

func (q *Queries) GetOpenIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, getOpenIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.IncidentID,
			&i.ChannelID,
			&i.SlackTs,
			&i.Alert,
			&i.Service,
			&i.Priority,
			&i.Attrs,
			&i.StartTimestamp,
			&i.EndTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openIncident = `-- name: OpenIncident :one
INSERT INTO incidents (
    channel_id,
    slack_ts,
    alert,
    service,
    priority,
    attrs,
    start_timestamp
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (channel_id, slack_ts)
DO UPDATE SET
    alert = EXCLUDED.alert
RETURNING incident_id
`

type OpenIncidentParams struct {
	ChannelID      string
	SlackTs        string
	Alert          string
	Service        string
	Priority       string
	Attrs          dto.IncidentAttrs
	StartTimestamp pgtype.Timestamptz
}

func (q *Queries) OpenIncident(ctx context.Context, arg OpenIncidentParams) (int32, error) {
	row := q.db.QueryRow(ctx, openIncident,
		arg.ChannelID,
		arg.SlackTs,
		arg.Alert,
		arg.Service,
		arg.Priority,
		arg.Attrs,
		arg.StartTimestamp,
	)
	var incident_id int32
	err := row.Scan(&incident_id)
	return incident_id, err
}
