// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package schema

import (
	dto "github.com/dynoinc/ratchet/internal/storage/schema/dto"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ChannelsV2 struct {
	ID    string
	Attrs dto.ChannelAttrs
}

type Llmusage struct {
	ID        int32
	Input     dto.LLMInput
	Output    dto.LLMOutput
	Model     string
	Prompt    string
	Timestamp pgtype.Timestamptz
}

type MessagesV3 struct {
	ChannelID string
	Ts        string
	ParentTs  *string
	Attrs     dto.MessageAttrs
	Embedding *pgvector.Vector
	Tsvec     interface{}
}
