// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reports.sql

package schema

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    channel_id,
    report_period_start,
    report_period_end,
    report_data
) VALUES (
    $1, $2, $3, $4
) RETURNING id, channel_id, report_period_start, report_period_end, report_data, created_at
`

type CreateReportParams struct {
	ChannelID         string
	ReportPeriodStart pgtype.Timestamptz
	ReportPeriodEnd   pgtype.Timestamptz
	ReportData        []byte
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ChannelID,
		arg.ReportPeriodStart,
		arg.ReportPeriodEnd,
		arg.ReportData,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ReportPeriodStart,
		&i.ReportPeriodEnd,
		&i.ReportData,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelReportsList = `-- name: GetChannelReportsList :many
SELECT id, channel_id, report_period_start, report_period_end, created_at
FROM reports
WHERE channel_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetChannelReportsListParams struct {
	ChannelID string
	Limit     int32
}

type GetChannelReportsListRow struct {
	ID                int32
	ChannelID         string
	ReportPeriodStart pgtype.Timestamptz
	ReportPeriodEnd   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) GetChannelReportsList(ctx context.Context, arg GetChannelReportsListParams) ([]GetChannelReportsListRow, error) {
	rows, err := q.db.Query(ctx, getChannelReportsList, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelReportsListRow
	for rows.Next() {
		var i GetChannelReportsListRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ReportPeriodStart,
			&i.ReportPeriodEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReport = `-- name: GetReport :one
SELECT id, channel_id, report_period_start, report_period_end, report_data, created_at
FROM reports
WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id int32) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ReportPeriodStart,
		&i.ReportPeriodEnd,
		&i.ReportData,
		&i.CreatedAt,
	)
	return i, err
}
