// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: thread_messages.sql

package schema

import (
	"context"

	dto "github.com/dynoinc/ratchet/internal/storage/schema/dto"
)

const addThreadMessage = `-- name: AddThreadMessage :exec
INSERT INTO thread_messages_v2 (channel_id, parent_ts, ts, attrs)
VALUES ($1, $2, $3, $4)
ON CONFLICT (channel_id, parent_ts, ts) DO NOTHING
`

type AddThreadMessageParams struct {
	ChannelID string
	ParentTs  string
	Ts        string
	Attrs     dto.ThreadMessageAttrs
}

func (q *Queries) AddThreadMessage(ctx context.Context, arg AddThreadMessageParams) error {
	_, err := q.db.Exec(ctx, addThreadMessage,
		arg.ChannelID,
		arg.ParentTs,
		arg.Ts,
		arg.Attrs,
	)
	return err
}
