// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package schema

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SlackChannel struct {
	ChannelID string
	TeamName  string
	Enabled   bool
	CreatedAt pgtype.Timestamp
}
