name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
          enable-cache: true

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Ruff formatter
      run: uv run ruff format . --check --diff

    - name: Ruff linter
      run: uv run ruff check --output-format=github .

    - name: Run tests
      run: uv run pytest tests
